package view;


public interface IComandMenu {
    String WATCH_ALL_STUDENTS = "WATCH_ALL_STUDENTS";
    String ADD_STUDENT = "ADD_STUDENT";
    String EXIT = "EXIT";
    String ALL_STUDENTS = "ALL_STUDENTS";
    String ENTER_STUDENT_LASTNAME = "ENTER_STUDENT_LASTNAME";
    String ENTER_STUDENT_FIRSTNAME = "ENTER_STUDENT_FIRSTNAME";
    String ENTER_BIRTHDAY = "ENTER_BIRTHDAY";
    String ENTER_PHONEnUMBER = "ENTER_PHONENUMBER";
    String ENTER_ADDRESS = "ENTER_ADDRESS";
    String WRONG_ENTER = "WRONG_ENTER";
}
