package view;


public interface IComandMenu {
    String WATCH_ALL_STUDENTS = "WATCH_ALL_STUDENTS";
    String ADD_STUDENT = "ADD_STUDENT";
    String EXIT = "EXIT";
    String ALL_STUDENTS = "ALL_STUDENTS";
    String ENTER_STUDENT_LASTNAME = "ENTER_STUDENT_LASTNAME";
    String ENTER_STUDENT_FIRSTNAME = "ENTER_STUDENT_FIRSTNAME";
    String LASTNAME_PATTERN = "LASTNAME_PATTERN";
    String FIRSTNAME_PATTERN = "FIRSTNAME_PATTERN";
    String ENTER_BIRTHDAY = "ENTER_BIRTHDAY";
    String BIRTHDAY_PATTERN = "BIRTHDAY_PATTERN";
    String ENTER_PHONENUMBER = "ENTER_PHONENUMBER";
    String PHONENUMBER_PATTERN= "PHONENUMBER_PATTERN";
    String ADDRESS_PATTERN = "ADDRESS_PATTERN";
    String ENTER_ADDRESS = "ENTER_ADDRESS";
    String WRONG_ENTER = "WRONG_ENTER";
}
